# Generated by Django 5.2.9 on 2025-12-05 20:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('unidade_medida', models.CharField(choices=[('min', 'Minutos'), ('km', 'Quilômetros'), ('kg', 'Quilogramas'), ('rep', 'Repetições'), ('out', 'Outro')], max_length=5)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Individuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor_alcançado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacoes', models.TextField(blank=True)),
                ('individuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='treinamento.individuo')),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.treinamento')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('individuo', 'treinamento', 'data')},
            },
        ),
    ]
