# Generated by Django 5.2 on 2025-12-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
