# Generated by Django 6.0 on 2025-12-06 21:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0002_individuo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuo',
            name='nome_completo',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e espaços', regex='^[A-Za-zÀ-ÿ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='registrotreinamento',
            name='observacoes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='registrotreinamento',
            name='valor_alcançado',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('999999.99'))]),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='O nome do treinamento deve conter apenas letras, números, espaços, hífens e pontos', regex='^[A-Za-zÀ-ÿ0-9\\s\\-\\.]+$')]),
        ),
    ]
