# Generated by Django 5.2 on 2025-12-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0003_alter_individuo_nome_completo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('puzzle_pieces', models.JSONField()),
                ('solution', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_solved', models.BooleanField(default=False)),
            ],
        ),
    ]
