# Generated by Django 5.2 on 2025-12-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0004_puzzlecaptcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('letters', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_solved', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='PuzzleCaptcha',
        ),
    ]
