# Generated by Django 5.2 on 2025-12-24 11:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0005_lettercaptcha_delete_puzzlecaptcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotreinamento',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrotreinamento',
            name='esforco_percebido',
            field=models.IntegerField(blank=True, help_text='Escala de 1 a 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='registrotreinamento',
            name='esporte',
            field=models.CharField(choices=[('corrida', 'Corrida'), ('ciclismo', 'Ciclismo'), ('caminhada', 'Caminhada'), ('natacao', 'Natação'), ('musculacao', 'Musculação'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        migrations.AddField(
            model_name='registrotreinamento',
            name='percurso_gps',
            field=models.JSONField(blank=True, help_text='Dados de GPS em formato GeoJSON ou lista de coordenadas', null=True),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('individuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.individuo')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='treinamento.registrotreinamento')),
            ],
        ),
        migrations.CreateModel(
            name='Kudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('individuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.individuo')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos', to='treinamento.registrotreinamento')),
            ],
            options={
                'unique_together': {('registro', 'individuo')},
            },
        ),
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='treinamento.individuo')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguindo', to='treinamento.individuo')),
            ],
            options={
                'unique_together': {('seguidor', 'seguido')},
            },
        ),
    ]
