# Generated by Django 5.2 on 2025-12-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0006_registrotreinamento_duracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuo',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações/restrições', max_length=500),
        ),
        migrations.AddField(
            model_name='individuo',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso em kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='individuo',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=10, null=True),
        ),
    ]
