# Generated by Django 5.2 on 2025-12-29 22:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0007_individuo_observacoes_individuo_peso_individuo_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=5)),
                ('data_registro', models.DateField(default=django.utils.timezone.now, help_text='Data do registro de peso')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a medição', max_length=500)),
                ('individuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_pesos', to='treinamento.individuo')),
            ],
            options={
                'ordering': ['-data_registro'],
                'unique_together': {('individuo', 'data_registro')},
            },
        ),
    ]
