# Generated by Django 5.2 on 2025-12-31 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0008_pesohistorico'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrotreinamento',
            unique_together=set(),
        ),
    ]
