# Generated by Django 6.0.1 on 2026-01-23 21:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0009_alter_registrotreinamento_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotreinamento',
            name='confiabilidade',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Score de confiabilidade dos dados (0-100%)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='registrotreinamento',
            name='fonte_dados',
            field=models.CharField(choices=[('manual', 'Entrada Manual'), ('iot', 'Dispositivo IoT'), ('api', 'API Externa')], default='manual', help_text='Origem dos dados', max_length=10),
        ),
        migrations.CreateModel(
            name='DispositivoIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='ID único do dispositivo (ex: ESP32_001)', max_length=100, unique=True)),
                ('nome', models.CharField(help_text='Nome amigável do dispositivo', max_length=200)),
                ('tipo', models.CharField(choices=[('heartrate', 'Monitor de Frequência Cardíaca'), ('steps', 'Contador de Passos'), ('weight', 'Balança Inteligente'), ('reps', 'Contador de Repetições'), ('gps', 'Rastreador GPS'), ('temperature', 'Sensor de Temperatura'), ('generic', 'Genérico')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('maintenance', 'Manutenção'), ('offline', 'Offline')], default='active', max_length=20)),
                ('ultimo_ping', models.DateTimeField(blank=True, help_text='Última vez que o dispositivo enviou dados', null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('mac_address', models.CharField(blank=True, help_text='Endereço MAC do dispositivo', max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('proprietario', models.ForeignKey(blank=True, help_text='Dono do dispositivo (opcional para dispositivos compartilhados)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_iot', to='treinamento.individuo')),
            ],
            options={
                'verbose_name': 'Dispositivo IoT',
                'verbose_name_plural': 'Dispositivos IoT',
                'ordering': ['-ultimo_ping'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_leitura', models.IntegerField(default=60, help_text='Intervalo entre leituras em segundos', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)])),
                ('valor_minimo_alerta', models.DecimalField(blank=True, decimal_places=2, help_text='Valor mínimo para gerar alerta', max_digits=10, null=True)),
                ('valor_maximo_alerta', models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo para gerar alerta', max_digits=10, null=True)),
                ('criar_registro_automatico', models.BooleanField(default=True, help_text='Criar automaticamente registros de treinamento')),
                ('fator_calibracao', models.DecimalField(decimal_places=3, default=1.0, help_text='Fator de calibração para ajustar leituras', max_digits=5)),
                ('offset_calibracao', models.DecimalField(decimal_places=2, default=0.0, help_text='Offset para ajustar leituras', max_digits=10)),
                ('configuracoes_extras', models.JSONField(blank=True, help_text='Configurações específicas do dispositivo', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('treinamento_padrao', models.ForeignKey(blank=True, help_text='Tipo de treinamento padrão para este dispositivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='treinamento.treinamento')),
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='treinamento.dispositivoiot')),
            ],
            options={
                'verbose_name': 'Configuração de Dispositivo',
                'verbose_name_plural': 'Configurações de Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='LeituraIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Timestamp da leitura do sensor')),
                ('tipo_sensor', models.CharField(help_text='Tipo de sensor (heartrate, steps, etc)', max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da leitura', max_digits=10)),
                ('unidade', models.CharField(help_text='Unidade de medida (bpm, steps, kg, etc)', max_length=20)),
                ('qualidade_sinal', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Bom'), ('fair', 'Razoável'), ('poor', 'Ruim')], default='good', max_length=20)),
                ('nivel_bateria', models.IntegerField(blank=True, help_text='Nível de bateria do dispositivo (%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('metadata', models.JSONField(blank=True, help_text='Dados adicionais do sensor (coordenadas GPS, etc)', null=True)),
                ('processado', models.BooleanField(default=False, help_text='Indica se a leitura já foi processada e convertida em registro de treinamento')),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='treinamento.dispositivoiot')),
                ('individuo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leituras_iot', to='treinamento.individuo')),
                ('registro_treinamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras_origem', to='treinamento.registrotreinamento')),
            ],
            options={
                'verbose_name': 'Leitura IoT',
                'verbose_name_plural': 'Leituras IoT',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertaIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('low_value', 'Valor Baixo'), ('high_value', 'Valor Alto'), ('offline', 'Dispositivo Offline'), ('low_battery', 'Bateria Baixa'), ('error', 'Erro no Sensor')], max_length=20)),
                ('severidade', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('critical', 'Crítico')], default='warning', max_length=20)),
                ('mensagem', models.TextField(help_text='Descrição do alerta')),
                ('visualizado', models.BooleanField(default=False)),
                ('resolvido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('visualizado_em', models.DateTimeField(blank=True, null=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('individuo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_iot', to='treinamento.individuo')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='treinamento.dispositivoiot')),
                ('leitura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='treinamento.leituraiot')),
            ],
            options={
                'verbose_name': 'Alerta IoT',
                'verbose_name_plural': 'Alertas IoT',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='leituraiot',
            index=models.Index(fields=['-timestamp'], name='treinamento_timesta_d3e4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='leituraiot',
            index=models.Index(fields=['dispositivo', '-timestamp'], name='treinamento_disposi_03a69b_idx'),
        ),
        migrations.AddIndex(
            model_name='leituraiot',
            index=models.Index(fields=['individuo', '-timestamp'], name='treinamento_individ_c77415_idx'),
        ),
    ]
