# Generated by Django 6.0.1 on 2026-01-23 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0010_registrotreinamento_confiabilidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotreinamento',
            name='confiabilidade',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Score de confiabilidade dos dados (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
