# Generated by Django 6.0.1 on 2026-01-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0011_alter_registrotreinamento_confiabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivoiot',
            name='forcar_offline',
            field=models.BooleanField(default=False, help_text='Marque para forçar o dispositivo como offline manualmente'),
        ),
    ]
