# Generated by Django 6.0.2 on 2026-04-03 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0012_dispositivoiot_forcar_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuo',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX ou XXXXXXXXXXX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$|^\\d{11}$')]),
        ),
        migrations.AddField(
            model_name='individuo',
            name='endereco',
            field=models.TextField(blank=True, help_text='Endereço completo', max_length=500),
        ),
        migrations.AddField(
            model_name='individuo',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone para contato', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve conter apenas números, espaços, hífens, parênteses e +', regex='^[\\d\\s\\-\\(\\)\\+]+$')]),
        ),
    ]
