# Generated by Django 6.0.2 on 2026-04-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0013_individuo_cpf_individuo_endereco_individuo_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individuo',
            name='endereco',
        ),
        migrations.AddField(
            model_name='individuo',
            name='endereco_bairro',
            field=models.CharField(blank=True, help_text='Bairro ou distrito', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='individuo',
            name='endereco_cep',
            field=models.CharField(blank=True, help_text='CEP no formato 00000-000', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='individuo',
            name='endereco_cidade',
            field=models.CharField(blank=True, help_text='Cidade', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='individuo',
            name='endereco_complemento',
            field=models.CharField(blank=True, help_text='Apartamento, bloco, sala, etc.', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='individuo',
            name='endereco_estado',
            field=models.CharField(blank=True, help_text='Estado (sigla, ex: SP, RJ, MG)', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='individuo',
            name='endereco_numero',
            field=models.CharField(blank=True, help_text="Número da residência (ou 'S/N' para sem número)", max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='individuo',
            name='endereco_pais',
            field=models.CharField(blank=True, default='Brasil', help_text='País', max_length=50, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='individuo',
            name='endereco_rua',
            field=models.CharField(blank=True, help_text='Nome da rua ou avenida', max_length=255, verbose_name='Rua/Av'),
        ),
    ]
